-- MySQL Workbench Forward Engineering
-- This script has been generated by the Workbench Forward Engineering functionality.
-- This script has been generated after modeling the database schema

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pay_my_buddy_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pay_my_buddy_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pay_my_buddy_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pay_my_buddy_db` ;

-- -----------------------------------------------------
-- Table `pay_my_buddy_db`.`associated_bank_account_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pay_my_buddy_db`.`associated_bank_account_info` (
  `associated_bank_account_info_id` INT NOT NULL AUTO_INCREMENT,
  `bank_account_holder_first_name` VARCHAR(45) NOT NULL,
  `bank_account_holder_last_name` VARCHAR(45) NOT NULL,
  `bic` VARCHAR(15) NOT NULL,
  `iban` VARCHAR(34) NOT NULL,
  PRIMARY KEY (`associated_bank_account_info_id`),
  UNIQUE INDEX `UK_hgkdery8n6fsnbahfn5jf2jwq` (`bic` ASC) VISIBLE,
  UNIQUE INDEX `UK_j4o01tjxdvceb96h5a0ql5a8b` (`iban` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pay_my_buddy_db`.`buddy_account_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pay_my_buddy_db`.`buddy_account_info` (
  `buddy_account_info_id` INT NOT NULL AUTO_INCREMENT,
  `account_balance` DOUBLE NOT NULL,
  `associated_bank_account_info_id` INT NOT NULL,
  PRIMARY KEY (`buddy_account_info_id`),
  INDEX `FKt7y7yvh9n3nfqne3rh8mkod80` (`associated_bank_account_info_id` ASC) VISIBLE,
  CONSTRAINT `FKt7y7yvh9n3nfqne3rh8mkod80`
    FOREIGN KEY (`associated_bank_account_info_id`)
    REFERENCES `pay_my_buddy_db`.`associated_bank_account_info` (`associated_bank_account_info_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pay_my_buddy_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pay_my_buddy_db`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(80) NOT NULL,
  `birth_date` DATE NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `civility` VARCHAR(5) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `phone` VARCHAR(10) NOT NULL,
  `role` VARCHAR(10) NOT NULL,
  `zip` VARCHAR(5) NOT NULL,
  `buddy_account_info_id` INT NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `UK_ob8kqyqqgmefl0aco34akdtpe` (`email` ASC) VISIBLE,
  INDEX `FKnvrlr4xsxpjhveo5eltn92hld` (`buddy_account_info_id` ASC) VISIBLE,
  CONSTRAINT `FKnvrlr4xsxpjhveo5eltn92hld`
    FOREIGN KEY (`buddy_account_info_id`)
    REFERENCES `pay_my_buddy_db`.`buddy_account_info` (`buddy_account_info_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pay_my_buddy_db`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pay_my_buddy_db`.`contacts` (
  `user_id` INT NOT NULL,
  `contact_id` INT NOT NULL,
  PRIMARY KEY (`user_id`, `contact_id`),
  INDEX `FKrs3dlygg4whsg3wi9eiuh58m7` (`contact_id` ASC) VISIBLE,
  CONSTRAINT `FKf9pc3faerry2wp3xnahv2b0rg`
    FOREIGN KEY (`user_id`)
    REFERENCES `pay_my_buddy_db`.`user` (`user_id`),
  CONSTRAINT `FKrs3dlygg4whsg3wi9eiuh58m7`
    FOREIGN KEY (`contact_id`)
    REFERENCES `pay_my_buddy_db`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pay_my_buddy_db`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pay_my_buddy_db`.`transaction` (
  `transaction_id` INT NOT NULL AUTO_INCREMENT,
  `amount` DOUBLE NOT NULL,
  `transaction_date` DATETIME(6) NOT NULL,
  `transaction_nature` VARCHAR(25) NOT NULL,
  `transaction_status_info` VARCHAR(25) NOT NULL,
  `buddy_account_info_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`transaction_id`),
  INDEX `FKhs6tv8p007u7yivaaowp3uqkt` (`buddy_account_info_id` ASC) VISIBLE,
  CONSTRAINT `FKhs6tv8p007u7yivaaowp3uqkt`
    FOREIGN KEY (`buddy_account_info_id`)
    REFERENCES `pay_my_buddy_db`.`buddy_account_info` (`buddy_account_info_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 37
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
